# Ironbar Configuration

position: top
height: 18

start:
- type: label
  name: custom-arch
  label: "󰣇"
- type: workspaces
  all_outputs: = true
  show_empty: false
  hidden: 
    - "special:S-obsidian"
    - "special:S-pavucontrol"
    - "special:magic"
  name_map:
    1: "1" # ""
    2: "2" # ""
    3: "3" # "󰿎"
    4: "4" # ""
    5: "5"
    6: "6"
    7: "7"
    8: "8"
    9: "9" # "󰢹"
    10: "10" # ""

center:
- type: focused
  icon_size: 16

end:
# - type: label
  # name: network
  # label: "Ethernet"
  
# - type: network_manager
  # icon_size: 16
  # format: " {essid}"
  # on_click_left: "nm-applet"
  
- type: volume
  format: "{icon} {percentage}%"
  on_click_left: "pavucontrol"
  on_click_right: "flatpak run io.github.ebonjaeger.bluejay"
- type: clock
  format: " %a %d %H:%M"
- type: battery
  format: "{icon} {percentage}%"
  show_if: |
    ls /sys/class/power_supply/ | grep --quiet '^BAT'
