[pyprland]
plugins = [
  "scratchpads",
]

[scratchpads.obsidian]
animation = "fromTop" 
command = "obsidian"
class = "obsidian" 
size = "90% 90%"
lazy = false

[scratchpads.youtubemusic]
animation = "fromTop"
command = "youtube-music"
class = "com.github.th_ch.youtube_music"
size = "90% 90%"
lazy = false
