description: Applications

packages:
  - brave-bin
  - obsidian
  - flatpak
  - syncthing
  - keepassxc
  - kdeconnect
  - nautilus
  - gnome-disk-utility
  - seahorse
  - gnome-keyring
  - trash-cli

post_install_hook: #scripts/setup-gaming.sh
hook_behavior: #ask
